### ISSUE TITLE
Error importing obspy

### ISSUE THREAD

**Issue by SeismoFelix** [uafgeotools/mtuq#158]
After the installation, I tried to run an example but there where an error when importing obspy

```
 python SerialGridSearch.DoubleCouple.py 

Traceback (most recent call last):
  File "SerialGridSearch.DoubleCouple.py", line 6, in <module>
    from mtuq import read, open_db, download_greens_tensors
  File "/Users/felix/Documents/INVESTIGACION/software/mtuq/mtuq/__init__.py", line 18, in <module>
    from mtuq.dataset import Dataset
  File "/Users/felix/Documents/INVESTIGACION/software/mtuq/mtuq/dataset.py", line 2, in <module>
    import obspy
  File "/Users/felix/opt/anaconda3/envs/mtuq/lib/python3.8/site-packages/obspy/__init__.py", line 39, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/Users/felix/opt/anaconda3/envs/mtuq/lib/python3.8/site-packages/obspy/core/__init__.py", line 124, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/Users/felix/opt/anaconda3/envs/mtuq/lib/python3.8/site-packages/obspy/core/utcdatetime.py", line 27, in <module>
    from obspy.core.util.deprecation_helpers import ObsPyDeprecationWarning
  File "/Users/felix/opt/anaconda3/envs/mtuq/lib/python3.8/site-packages/obspy/core/util/__init__.py", line 27, in <module>
    from obspy.core.util.base import (ALL_MODULES, DEFAULT_MODULES,
  File "/Users/felix/opt/anaconda3/envs/mtuq/lib/python3.8/site-packages/obspy/core/util/base.py", line 36, in <module>
    from obspy.core.util.misc import to_int_or_zero, buffered_load_entry_point
  File "/Users/felix/opt/anaconda3/envs/mtuq/lib/python3.8/site-packages/obspy/core/util/misc.py", line 214, in <module>
    loadtxt(np.array([0]), ndmin=1)
  File "/Users/felix/opt/anaconda3/envs/mtuq/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1086, in loadtxt
    ncols = len(usecols or split_line(first_line))
  File "/Users/felix/opt/anaconda3/envs/mtuq/lib/python3.8/site-packages/numpy/lib/npyio.py", line 977, in split_line
    line = line.split(comment, 1)[0]
AttributeError: 'numpy.int64' object has no attribute 'split'

```
When I try to use obspy in python 3.7 I have no problems. This only happens with mtuq environment (obspy in python 3.8).

**Comment by rmodrak** [comment]
Thank you for this report.  What is the full ObsPy version number you get from ``python --version``?

**Comment by SeismoFelix** [comment]
Python 3.8.12

**Comment by rmodrak** [comment]
I'm not getting the above error using Python 3.8.12, Numpy 1.21.4, ObsPy 1.2.2.  Since we are using the same versions of Python and ObsPy, perhaps it is mainly NumPy related?

As a quick check, have you tried using a minimal environment?  In other words, create a new Python 3.8.12 conda environment, then run only ``conda install numpy obspy``.  Do you get the same ObsPy import  using this environment?

**Comment by SeismoFelix** [comment]
Thanks. I proceeded like this:

```
conda config --prepend channels conda-forge
conda create -n mtuq python=3.8.12

conda activate mtuq
conda install numpy=1.21.4 obspy=1.2.2 instaseis
git clone https://github.com/uafgeotools/mtuq.git
cd mtuq
pip install -e .

bash ./data/examples/unpack.bash
bash ./data/tests/unpack.bash

conda install gmt=6.1
```

Then I moved to the examples directory and run: 

`python SerialGridSearch.DoubleCouple.py`

Unfortunately, I got the following error:
```

(mtuq) Felixs-iMac:examples felix$ python SerialGridSearch.DoubleCouple.py 
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "SerialGridSearch.DoubleCouple.py", line 6, in <module>
    from mtuq import read, open_db, download_greens_tensors
  File "/Users/felix/Documents/SOFTWARE/mtuq/mtuq/__init__.py", line 26, in <module>
    from mtuq.misfit import Misfit
  File "/Users/felix/Documents/SOFTWARE/mtuq/mtuq/misfit/__init__.py", line 2, in <module>
    from mtuq.misfit.waveform import Misfit
  File "/Users/felix/Documents/SOFTWARE/mtuq/mtuq/misfit/waveform/__init__.py", line 5, in <module>
    from mtuq.misfit.waveform import level0, level1, level2
  File "/Users/felix/Documents/SOFTWARE/mtuq/mtuq/misfit/waveform/level2.py", line 13, in <module>
    from mtuq.misfit.waveform import c_ext_L2
ImportError: numpy.core.multiarray failed to import
```

**Comment by SeismoFelix** [comment]
I downgraded  NumPy before compiling mtuq. However, I run build_ext.sh:

```
(mtuq) Felixs-iMac:mtuq felix$ sh build_ext.sh 
rm: mtuq/misfit/*.so: No such file or directory
running build_ext
building 'mtuq.misfit.waveform.c_ext_L2' extension
In file included from mtuq/misfit/waveform/c_ext_L2.c:3:
In file included from /Users/felix/opt/anaconda3/envs/mtuq/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /Users/felix/opt/anaconda3/envs/mtuq/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
In file included from /Users/felix/opt/anaconda3/envs/mtuq/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1969:
/Users/felix/opt/anaconda3/envs/mtuq/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "
      "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it with " \
 ^
1 warning generated.
copying build/lib.macosx-10.9-x86_64-3.8/mtuq/misfit/waveform/c_ext_L2.cpython-38-darwin.so -> mtuq/misfit/waveform
```
Then I run the example SerialGridSearch.DoubleCouple.py and worked. 

```
(mtuq) Felixs-iMac:examples felix$ python SerialGridSearch.DoubleCouple.py 
Reading data...

Processing data...

Reading Greens functions...

 Downloading Greens functions for station BIGB
 Downloading Greens functions for station PMR
 Downloading Greens functions for station KASH
 Downloading Greens functions for station TUPA
 Downloading Greens functions for station LSUM
 Downloading Greens functions for station MPEN
 Downloading Greens functions for station DEVL
 Downloading Greens functions for station BLAK
 Downloading Greens functions for station LSKI
 Downloading Greens functions for station NSKI
 Downloading Greens functions for station AVAL
 Downloading Greens functions for station PERI
 Downloading Greens functions for station SOLD
 Downloading Greens functions for station SWD
 Downloading Greens functions for station HEAD
 Downloading Greens functions for station DIV
 Downloading Greens functions for station TRF
 Downloading Greens functions for station EYAK
 Downloading Greens functions for station PAX
 Downloading Greens functions for station BMR
Processing Greens functions...

Evaluating body wave misfit...

  Number of misfit evaluations: 6.400e+04

  about 0 percent finished
  about 25 percent finished
  about 50 percent finished
  about 75 percent finished
  Elapsed time (s): 2.554374

Evaluating surface wave misfit...

  Number of misfit evaluations: 6.400e+04

  about 0 percent finished
  about 25 percent finished
  about 50 percent finished
  about 75 percent finished
  Elapsed time (s): 17.283173

Generating figures...

Saving results...

  saving NetCDF file: 20090407201255351DC_misfit.nc

Finished

```
Thank you so much for your aid. 
![20090407201255351DC_waveforms](https://user-images.githubusercontent.com/18186011/154202090-277199f1-258c-4f46-a84d-0a9fc9172ba2.png)
