### ISSUE TITLE
Plotting with a single station

### ISSUE THREAD

**Issue by SeismoFelix** [uafgeotools/mtuq#171]
It seems that MTUQ is not implemented for single-station plotting, although the grid-search seems to work well. 

I have this error and no files are generated (NetCDF, JSON, ps, and png): 

Generating figures...

Traceback (most recent call last):
  File "/home/jovyan/scoped/mtuq_workshop_2022/GridSearch.DoubleCouple_options.py", line 235, in <module>
    plot_data_greens2(event_id+'DC_waveforms.png',
  File "/home/jovyan/scoped/mtuq/mtuq/graphics/waveforms.py", line 314, in plot_data_greens2
    plot_waveforms2(filename,
  File "/home/jovyan/scoped/mtuq/mtuq/graphics/waveforms.py", line 134, in plot_waveforms2
    fig, axes = _initialize(
  File "/home/jovyan/scoped/mtuq/mtuq/graphics/waveforms.py", line 357, in _initialize
    _hide_axes(axes)
  File "/home/jovyan/scoped/mtuq/mtuq/graphics/waveforms.py", line 643, in _hide_axes
    for col in row:
TypeError: 'AxesSubplot' object is not iterable

**Comment by rmodrak** [comment]
Hi Felix,

Good point, the waveform figures are based on
```
fig, axes = matplotlib.subplots(nrows, ncolumns)
```
but this function itself is not very robust for nrows=1.

As a fix, I think we just add
```
if len(nrows)==1:
    axes = [axes]
```
or something similar.  We can add to the next pull request.

Thanks for this report. 

-Ryan

**Comment by rmodrak** [comment]
Soon to be merged from [here](https://github.com/uafgeotools/mtuq/commit/4550ef17b1764bd4f81cfe6993a61de4ab941f6a)
