### ISSUE TITLE
Using both HN* and BH* components for a single station

### ISSUE THREAD

**Issue by ammcpherson** [uafgeotools/mtuq#246]
A somewhat niche case, but recently I was trying to use both the broadband components and the strong motion data from 2 stations, and discovered that MTUQ cannot handle this. I get the following error where both types of traces are present in my data directory:

`Traceback (most recent call last):
  File "run_mtuq.py", line 179, in <module>
    data = read(path_data, 
  File "/home/ammcpherson/REPOSITORIES/mtuq/mtuq/__init__.py", line 86, in read
    return _readers()[format](path, **kwargs)
  File "/home/ammcpherson/REPOSITORIES/mtuq/mtuq/io/readers/SAC.py", line 73, in read
    check_components(stream)
  File "/home/ammcpherson/REPOSITORIES/mtuq/mtuq/util/signal.py", line 212, in check_components
    raise Exception('Multiple %s components in stream' % component)
Exception: Multiple R components in stream`

It would be nice if MTUQ could handle this in a similar vein to how it handles multiple location codes, and use both the strong motion and broadband data in the inversion.

**Comment by rmodrak** [comment]
Did you try commenting out ``check_components`` by chance?  It's possible then though the runtime error may just be deferred until later (e.g. the misfit function may not currently be able to handle multiple components of the same type)

**Comment by ammcpherson** [comment]
Hi @rmodrak,

Sorry for the long time between responses. I'm coming back to this now.

I just commented out `check_components` in `/mtuq/io/readers/SAC.py` and MTUQ no longer crashes. However, this does not produce the desired waveform plots either:
<img width="788" alt="Screen Shot 2024-02-28 at 11 13 48" src="https://github.com/uafgeotools/mtuq/assets/29667569/4c25d674-9b7e-40c7-8b59-e4e5dec7c965">
The station in the red box are the stations for which we have both broadband and strong motion data. We'd like them to be both plotted in a similar manner to the stations in the blue box, for which we have 2 separate location codes for the same physical location
